apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: azure-rediscache-hello-kyma
  labels: 
    app: hello-kyma
spec:
  instanceRef:
    name: azure-rediscache-personal-introduction

---
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: azure-rediscache-hello-kyma
  labels:
    app: hello-kyma
spec:
  parameters:
    envPrefix:
      name: "AZ_"
  serviceBindingRef:
    name: azure-rediscache-hello-kyma
  usedBy:
    kind: deployment
    name: hello-kyma

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: sap-commerce-hello-kyma
  labels: 
    app: hello-kyma
spec:
  instanceRef:
    name: sap-commerce-cloud-commerce-webservices

---
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: sap-commerce-hello-kyma
  labels:
    app: hello-kyma
spec:
 serviceBindingRef:
   name: sap-commerce-hello-kyma
 usedBy:
   kind: deployment
   name: hello-kyma